### ISSUE TITLE
Gas turbines with carbon capture?

### ISSUE THREAD

**Issue by koen-vg** [PyPSA/pypsa-eur#1084]
## Describe the feature you'd like to see

I am correct that the current sector-coupled version of the model actually doesn't have any support for gas turbines (open- or combined cycle) with carbon capture? (Or oil powerplants for that matter.) It seems like an obvious technology to add, along the lines of the existing `coal_cc` option.

Unless these is anything obvious I missed, I'd be happy to quickly add an option for this.

Maybe one question, configuration-wise, is how to organise all this conventional generation. It's arguably already a bit messy to have both the `conventional_generation` and `coal_cc` options in the `sector:` config. I would consider removing the `coal_cc` option and rather add some functionality to `add_generation` to parse whether each carrier ends in `_cc`. Then you could have (including as many technologies as possible):
```
conversional_generation:
  coal: coal
  coal_cc: coal
  lignite: lignite
  lignite_cc: lignite
  OCGT: gas
  OCGT_cc: gas
  CCGT: gas
  CCGT_cc: gas
  oil: oil
  oil_cc: oil
  nuclear: uranium
```

For the variants with carbon capture one could use costs, efficiencies, etc. from `biomass CHP capture` or `cement capture` parameters; both are used in `prepare_sector_network` but also they are almost identical.
