### ISSUE TITLE
override_components in config.yaml

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#122]
## Describe the feature you'd like to see

*Please give a clear and concise description and provide context why the feature would be useful.*
*Also, we'd appreciate any implementation ideas and references you already have.*

Following discussions/questions on the mailing list `Components disappear in snakefile execution`:

On keeping `override_components` throughout the workflow:
> Unfortunately not, however we are planning to make the imports more flexible in future versions. Perhaps we could even enable to add components globally through the snakefile... I think about it. 
For now I only see the two options: (1.)  adjusting every import in the scripts in pypsa-eur or (2.) changing your components.csv in your pypsa/pypsa folder. I would say the first option is the 'saver' one as you only modify one package. @FabianHofmann 

I thought of a way to maintain overwritten components through the `config.yaml`. This is just a sketch:

1. Add the definition of additional components to `config.yaml`, e.g.:

```yaml
override_components:
  ShadowPrice:
    component: ["shadow_prices","Shadow price for a global constraint.",np.nan]
    attributes:
      name: ["string","n/a","n/a","Unique name","Input (required)"]
      value: ["float","n/a",0.,"shadow value","Output"]
```

2. Write a function in `scripts/_helpers.py` to load `override_components` and `override_component_attrs` in the correct format:

```python
import pypsa
import pandas as pd
from pypsa.descriptors import Dict

def read_override_components(components):
    override_components = pypsa.components.components.copy()
    override_component_attrs = Dict({k : v.copy() for k,v in pypsa.components.component_attrs.items()})
    for k, v in components.items():
        override_components.loc[k] = v['component']
        override_component_attrs[k] = pd.DataFrame(columns = ["type","unit","default","description","status"])
        for attr, val in v['attributes'].items():
            override_component_attrs[k].loc[attr] = val
        
    return override_components, override_component_attrs
```

3. In all `scripts/*.py` where a network is imported, add

```python
x, y = read_override_components(snakemake.config['override_components'])
network = pypsa.Network(snakemake.input[0], override_components=x, override_component_attrs=y)
```
