### ISSUE TITLE
shared_resources not working for solve_sector_networks

### ISSUE THREAD

**Issue by bobbyxng** [PyPSA/pypsa-eur#1576]
## Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [X] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug
- In the latest master, `shared_resources: true` does not seem to be working anymore for sector-coupled runs. (`solve_elec_networks` still works with shared resources)

## Error Message
**MRE:** 
config.yaml: 
```
run:
  prefix: co2-path-comparison
  name: 
    - scenario_a
    - scenario_b
  scenarios:
    enable: true
    file: config/scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: True
    exclude: []
```
scenarios.yaml:
```
scenario_a:
  sector: 
    co2_budget:
      2020: 0.701
      2025: 0.524
      2030: 0.297
      2035: 0.150
      2040: 0.071
      2045: 0.032
      2050: 0.000

scenario_b:
  sector:
     co2_budget:
      2020: 0.701
      2025: 0.524
      2030: 0.297
      2035: 0.000
      2040: 0.000
      2045: 0.000
      2050: 0.000

```

**Error message**
```
Building DAG of jobs...
WildcardError in rule prepare_sector_network in file pypsa-eur/rules/build_sector.smk, line 1087:
Wildcards in params cannot be determined from output files. Note that you have to use a function to deactivate automatic wildcard expansion in params strings, e.g., `lambda wildcards: '{test}'`. Also see https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#non-file-parameters-for-rules: (rule prepare_sector_network, line 2196, pypsa-eur/rules/build_sector.smk)
'run'
```
