### ISSUE TITLE
Bug in solve_network (edge case)

### ISSUE THREAD

**Issue by Irieo** [PyPSA/pypsa-eur#1605]
## Checklist

- [x] I am using the current [`master`](https://github.com/PyPSA/pypsa-eur/tree/master) branch or the latest [release](https://github.com/PyPSA/pypsa-eur/releases). Please indicate.
- [x] I am running on an up-to-date [`pypsa-eur` environment](https://github.com/PyPSA/pypsa-eur/blob/master/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`.

## Describe the Bug

The workflow breaks in `solve_network.py` --- if the network does not have any links --- with an error
`AttributeError: Can only use .str accessor with string values!`

## Where is the problem 

The problem is in this line: https://github.com/PyPSA/pypsa-eur/blob/1c4b186c20a2762a285f66ebb977afb32c8d8fe0/scripts/solve_network.py#L1186-L1188

as this operation does not handle a case when index is empty.

## How to reproduce it

run our standard test config 
`$ snakemake solve_elec_networks --configfile config/test/config.electricity.yaml`

with these settings (w/o links).

```
  extendable_carriers:
    Generator: [OCGT]
    StorageUnit: [battery]
    Store: [] # diff to config.electricity.yaml
    Link: [] # diff to config.electricity.yaml
```
## How to fix

Add if clause checking that links are present.
