### ISSUE TITLE
reduce allowed deployment density of on-/offshore wind

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#210]
Change default setting to

```yaml
renewable:
  onwind:
    capacity_per_sqkm: 2 # ScholzPhd Tab 4.3.1: 10MW/km^2
```
