### ISSUE TITLE
Add `Citation.cff`

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#264]
https://twitter.com/natfriedman/status/1420122675813441540?s=20

**Comment by euronion** [comment]
That's nice!

Maybe we can create a pre-commit hook to automate the CFF creation using `doi2cff` ?
https://github.com/citation-file-format/doi2cff

We'd have to do some housekeeping on the archived release on Zenodo (author names). The current version yields this:

```
>doi2cff init 10.5281/zenodo.4309093

# YAML 1.2
# Metadata for citation of this software according to the CFF format (https://citation-file-format.github.io/)
cff-version: 1.0.3
message: If you use this software, please cite it using these metadata.
# FIXME title as repository name might not be the best name, please make human readable
title: 'PyPSA/pypsa-eur: v0.3.0'
doi: 10.5281/zenodo.4309093
# FIXME splitting of full names is error prone, please check if given/family name are correct
authors:
- given-names: Jonas
  family-names: Hörsch
- given-names: Fabian
  family-names: Neumann
  affiliation: KIT
- given-names: FabianHofmann
  family-names: ''
- given-names: Jeroen
  family-names: Peters
- given-names: JanFrederickUnnewehr
  family-names: ''
- given-names: euronion
  family-names: ''
- given-names: Tom
  family-names: Brown
- given-names: Martha
  family-names: Maria
  affiliation: Karlsruhe Institute of Technology
- given-names: arnaud-leroy
  family-names: ''
  affiliation: KIT
- given-names: Max
  family-names: Parzen
  affiliation: University of Edinburgh
version: 0.3.0
date-released: 2020-12-07
repository-code: https://github.com/PyPSA/pypsa-eur
license: other-open
```

Also: Should the software release be cited using the `CITATIONS.cff` or the original paper? (I'd say the first one is the correct one, the second option the common one).
