### ISSUE TITLE
Add documentation links to solver options into config.default.yaml

### ISSUE THREAD

**Issue by coroa** [PyPSA/pypsa-eur#486]
I found the link to the documentation of the solver options incredibly helpful, should we add them directly to the config?

Ie.
```yaml
solver_options:
    highs-default:
      # refer to https://ergo-code.github.io/HiGHS/options/definitions.html#solver
      threads: 4
      solver: "ipm"
      run_crossover: "off"
      small_matrix_value: 1e-6
      large_matrix_value: 1e9
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      ipm_optimality_tolerance: 1e-4
      parallel: "on"
      random_seed: 123
```

idea pulled from https://github.com/PyPSA/pypsa-eur-sec/pull/318#discussion_r1124167765 .
