### ISSUE TITLE
Document new config entries for perfect foresight optimisation

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#749]
#637 added new config entries which are currently undocumented. These should be added to

- https://github.com/PyPSA/pypsa-eur/blob/master/doc/configtables/sector.csv
- https://github.com/PyPSA/pypsa-eur/blob/master/doc/configtables/costs.csv

```yaml
sector:
  co2_sequestration_lifetime: 50
  limit_max_growth:
    enable: false
    # allowing 30% larger than max historic growth
    factor: 1.3
    max_growth:  # unit GW
      onwind: 16 # onshore max grow so far 16 GW in Europe https://www.iea.org/reports/renewables-2020/wind
      solar: 28 # solar max grow so far 28 GW in Europe https://www.iea.org/reports/renewables-2020/solar-pv
      offwind-ac: 35 # offshore max grow so far 3.5 GW in Europe https://windeurope.org/about-wind/statistics/offshore/european-offshore-wind-industry-key-trends-statistics-2019/
      offwind-dc: 35
    max_relative_growth:
      onwind: 3
      solar: 3
      offwind-ac: 3
      offwind-dc: 3

costs:
  social_discountrate: 0.02
```
