### ISSUE TITLE
add extra_functionality constraints with cyclicity for short-term storage

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-eur#876]
i.e. same state of charge once a day, config:

```yaml
storage_cyclicity:
  home battery: 24
  battery: 24
  rural water tanks: 24
  urban decentral water tanks: 24
```

where value represents number of hours and keys represent the "Store" carrier.
